// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class AI_ControllerAlly : MonoBehaviour {

	public Transform[] spawnPositionsLeft;
	public Transform[] spawnPositionsRight;
	public GameObject skeletonPrefab;
	public GameObject darkKnightPrefab;
	public GameObject ogrePrefab;

	private TargetableByAIAlly[] targetsAlly;
	private MinionAlly[] minionsAlly;

	public static AI_ControllerAlly Instance { get; private set; }
	public float maxDistanceEngageMelee = 6;
	public float maxDistanceEngageRange = 30;
	public float maxDistanceEngageMagic = 15;

	void Awake () {
		if (Instance == null) {
			Instance = this;
		} else {
			Destroy(gameObject);
		}
	}
	void OnDestroy() {
		Instance = null;
	}


	void Start() {
		targetsAlly = FindObjectsOfType<TargetableByAIAlly>();
	}


	private void SendMinionsFight() {
		foreach(MinionAlly minion in minionsAlly) {
			minion.Fight();
		}
	}

	private void CheckTargets() {
		int count = 0;
		foreach (TargetableByAIAlly targetAlly in targetsAlly) {
			count++;
		}
		if (count == 0) {
			targetsAlly = FindObjectsOfType<TargetableByAIAlly> ();
		}
	}

	/**
	 * Ally target
	 */
	private TargetableByAIAlly GetRandomTargetAlly() {
		return targetsAlly[ UnityEngine.Random.Range(0, targetsAlly.Length) ];
	}

	public TargetableByAIAlly GetClosestTargetAlly(Vector3 position, string type) {
		float minDistance = 99999;
		float maxDistanceEngage = GetDistanceEngageMax (type);
		TargetableByAIAlly closestTarget = null;

		/*Debug.Log (targetsAlly);
		CheckTargets ();
		Debug.Log (targetsAlly);*/
		foreach (TargetableByAIAlly targetAlly in targetsAlly) {
			if ((targetAlly != null) && (!targetAlly.GetComponent<Alive> ().IsDead)) {
				float distance = Vector3.Distance (position, targetAlly.transform.position);
				if (((distance < minDistance) || (closestTarget == null)) && (distance < maxDistanceEngage)) {
					minDistance = distance;
					closestTarget = targetAlly;
				}
			}
		}

		return closestTarget;
	}

	public bool AreAllMinionsDead() {
		foreach(MinionAlly minion in minionsAlly) {
			if ((minion != null) && !minion.IsDead()) {
				return false;
			}
		}
		return true;
	}

	public void SendWave_1() {
		// SpawnSkeletonOnRight();
		// SpawnSkeletonOnRight();

		StartCoroutine( ReleaseWave() );
	}

	public void SendWave_2() {
		SpawnSkeletonAnywhere();
		SpawnSkeletonAnywhere();
		SpawnSkeletonAnywhere();

		StartCoroutine( ReleaseWave() );
	}

	public void SendWave_3() {
		SpawnDarkKnightAnywhere();
		SpawnDarkKnightAnywhere();

		StartCoroutine( ReleaseWave() );
	}

	public void SendWave_4() {
		SpawnOgreAnywhere();

		StartCoroutine( ReleaseWave() );
	}

	public void SendWave_5() {
		SpawnOgreAnywhere();
		SpawnOgreAnywhere();
		SpawnOgreAnywhere();
		SpawnOgreAnywhere();
		SpawnOgreAnywhere();

		StartCoroutine( ReleaseWave() );
	}

	private IEnumerator ReleaseWave() {
		yield return 0;
		minionsAlly = FindObjectsOfType<MinionAlly>();
		SendMinionsFight();
	}


	private Transform GetLeftSpawnPosition() {
		return spawnPositionsLeft[ UnityEngine.Random.Range(0, spawnPositionsLeft.Length) ];
	}
	private Transform GetRightSpawnPosition() {
		return spawnPositionsRight[ UnityEngine.Random.Range(0, spawnPositionsRight.Length) ];
	}

	private void SpawnMinionOnLeft(GameObject minionPrefab) {
		Instantiate(minionPrefab, GetLeftSpawnPosition().position, Quaternion.identity);
	}
	private void SpawnMinionOnRight(GameObject minionPrefab) {
		Instantiate(minionPrefab, GetRightSpawnPosition().position, Quaternion.identity);
	}
	private void SpawnMinionAnywhere(GameObject minionPrefab) {
		if (UnityEngine.Random.value < .5f) {
			SpawnMinionOnLeft(minionPrefab);
		} else {
			SpawnMinionOnRight(minionPrefab);
		}
	}

	private void SpawnSkeletonOnLeft() {
		SpawnMinionOnLeft(skeletonPrefab);
	}
	private void SpawnSkeletonOnRight() {
		SpawnMinionOnRight(skeletonPrefab);
	}
	private void SpawnSkeletonAnywhere() {
		SpawnMinionAnywhere(skeletonPrefab);
	}

	private void SpawnDarkKnightOnLeft() {
		SpawnMinionOnLeft(darkKnightPrefab);
	}
	private void SpawnDarkKnightOnRight() {
		SpawnMinionOnRight(darkKnightPrefab);
	}
	private void SpawnDarkKnightAnywhere() {
		SpawnMinionAnywhere(darkKnightPrefab);
	}

	private void SpawnOgreOnLeft() {
		SpawnMinionOnLeft(ogrePrefab);
	}
	private void SpawnOgreOnRight() {
		SpawnMinionOnRight(ogrePrefab);
	}
	private void SpawnOgreAnywhere() {
		SpawnMinionAnywhere(ogrePrefab);
	}

	public float GetDistanceEngageMax(string type) {
		float distance = 99999;
		if (type == "melee") {
			distance = maxDistanceEngageMelee;
		} else if (type == "range") {
			distance = maxDistanceEngageRange;
		} else if (type == "magic") {
			distance = maxDistanceEngageMagic;
		}
		return distance;
	}
}

